# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f3af2ffcb18caba26e0b1e444470832afe4d2c577d25acb9791dff956383c79694460ef53e60a6dd7fc5fc603a90f371388584e20db04666ec5dfebacb177b4

test:
  secret_key_base: be761a5fee14189d07d33d1a1bbe3721565d222ba548600f5f6807ad48c16e07446efd9f4049705fa5586a16ee8d05524a0ebf22a93b8ef3be412809e34ac9ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
